### ISSUE TITLE
[feature request] Introducing debug APIs

### ISSUE THREAD

**Issue by Avish34** [CRED-CLUB/propeller#52]
Hi @Abhishekvrshny,

I have a suggestion to improve the user's ability to debug issues while using this engine. Go offers a powerful tool called pprof, which can visualize various segments such as heap, goroutines, mutexes, and more. This tool is invaluable for analyzing performance, understanding scalability, and diagnosing issues effectively.

**Pros:**
Integrating pprof into the codebase would provide significant benefits. It allows developers to pinpoint performance bottlenecks and resource leaks efficiently, ultimately improving the system's reliability and maintainability. Additionally, its visualization capabilities make complex data easier to interpret, enabling faster debugging and optimization.

**Tool:**
https://pkg.go.dev/net/http/pprof

I would like to implement this feature if you agree there is a need for it. Please let me know your thoughts.

**Comment by rakshith-ravi** [comment]
Is pprof compatible with otel? If not, otel metrics pliss

**Comment by Avish34** [comment]
Thanks @Abhishekvrshny, I will open the PR shortly.

@rakshith-ravi I think both are different use cases, pprof is more for profiling the service, and on the other hand, open telemetry can be used for metrics, trace, and other similar use cases I believe.

**Comment by Avish34** [comment]
https://github.com/CRED-CLUB/propeller/pull/54
