### ISSUE TITLE
[Feature Request] Implementation of Security Middleware for gRPC server for closed infrastructure

### ISSUE THREAD

**Issue by PythonHacker24** [CRED-CLUB/propeller#61]
## Implementation of Security Middleware for gRPC server for closed infrastructure

Since the propeller is being used in production, implementing middleware that authenticates legitimate calls would enhance its security. 

There are two ways I can think of implementing security:
1. **API Keys through Headers:** Middleware will check the API key in the headers for each request and only authenticate legitimate callers. 
2. **IP Whitelisting:** Only authorized IPs can access the gRPC server. 

Now, since **we don't want to disrupt current implementations of propellers**, these features would be OFF by default and can be configured in the propeller.toml. So, the current implementations of the propeller would remain functional even after the update. 

Params like `EnableAPIAuth` and `EnableIPWhitelisting` can be added to `propeller.toml`. 

If not for all RPC calls, this functionality can be implemented in the server reflection feature, which would be added to the PR. 

Please let me know your suggestions and if I should work on it. 

Thanks

**Comment by Abhishekvrshny** [comment]
Hey @PythonHacker24 , thanks for the feature request. I agree that security is paramount to any piece of infrastructure and authentication and IP whitelisting are some of the ways to achieve the same. Propeller currently doesn't have any form of authentication or IP whitelisting as mentioned in the [docs](https://cred-club.github.io/propeller/concepts.html) as well. Propeller currently expects authentication and any other security check to happen outside of it. Most organizations have existing setups for Authentication, IP whitelisting, etc through API gateways generally which can help make propeller secure along with other services.

Is propeller something that you are deploying in your infra? If yes, what is the existing method of authentication for other APIs?

If we were to implement authentication in propeller, we would have to design it well gathering requirements from different clients before picking up the implementation.

**Comment by PythonHacker24** [comment]
I completely agree with it and the organization's reliance on API gateways, which makes the propeller service secure in their infra. 

In my experience, through working in a startup and moving on to building my products now, most small-scale startups don't rely heavily on API gateways (due to reasons like cost, prototyping, and fast-paced development) but mainly depend on the security features of the tool that comes with them. Users utilizing open-source projects expect a base-level functionality for topics like security (which, in this case, would be access control). 

API Gateways is undoubtedly a more secure and consistent way to protect infrastructure services. Still, simple base-level security features would help more users adopt Propeller exposure to the Internet or prevent insider attacks. Packing some authentication mechanisms would help Propeller become a complete toolkit for its purpose. 

We can implement this by supporting, not disrupting, current services and focusing on backward compatibility. For example, we can disable authentication by default and allow the Propeller to run without auth configs (optional configs). 

Let me know what you think.

Thanks

**Comment by Abhishekvrshny** [comment]
I would like to understand your use-case and setup better. How do you plan to use propeller? How does your current frontend and backend setup looks like? How are authentication and IP whitelisting handled in the current setup?

**Comment by PythonHacker24** [comment]
Our frontend (flutter application) and backend (golang) are paired with REST and communicate directly. We don't use intermediary services for communication since we are in the development and prototyping stage. We might use propeller in the future because of the requirements. 

The idea of implementing authentication into the propeller came from protecting server reflection when it is intentionally turned on or left on in production environments. Having a layer of authentication helps. These features enhance the propeller as a tool for integrating backends and frontends. 

I was going to work on this auth and whitelisting feature, so I considered asking you first whether we need it or if anything better can be done.

**Comment by PythonHacker24** [comment]
It more like an enhancement thing

**Comment by Abhishekvrshny** [comment]
Let's re-open this discussion once you are at the advanced stages of integrating propeller. We will have a more concrete understanding of the use case by then. Closing this for now.

**Comment by PythonHacker24** [comment]
Sure, I will let you know.
